// Generate PAX code //
conversion = real(argument0);
switch (conversion)
    {
    case 0: return "0"; break;
    case 1: return "1"; break;
    case 2: return "2"; break;
    case 3: return "3"; break;
    case 4: return "4"; break;
    case 5: return "5"; break;
    case 6: return "6"; break;
    case 7: return "7"; break;
    case 8: return "8"; break;
    case 9: return "9"; break;
    
    case 10: return "A"; break;
    case 11: return "B"; break;
    case 12: return "C"; break;
    case 13: return "D"; break;
    case 14: return "E"; break;
    case 15: return "F"; break;
    case 16: return "G"; break;
    case 17: return "H"; break;
    case 18: return "I"; break;
    case 19: return "J"; break;
    case 20: return "K"; break;
    case 21: return "L"; break;
    case 22: return "M"; break;
    case 23: return "N"; break;
    case 24: return "O"; break;
    case 25: return "P"; break;
    case 26: return "Q"; break;
    case 27: return "R"; break;
    case 28: return "S"; break;
    case 29: return "T"; break;
    case 30: return "U"; break;
    case 31: return "V"; break;
    case 32: return "W"; break;
    case 33: return "X"; break;
    case 34: return "Y"; break;
    case 35: return "Z"; break;
    
    case 36: return "a"; break;
    case 37: return "b"; break;
    case 38: return "c"; break;
    case 39: return "d"; break;
    case 40: return "e"; break;
    case 41: return "f"; break;
    case 42: return "g"; break;
    case 43: return "h"; break;
    case 44: return "i"; break;
    case 45: return "j"; break;
    case 46: return "k"; break;
    case 47: return "l"; break;
    case 48: return "m"; break;
    case 49: return "n"; break;
    case 50: return "o"; break;
    case 51: return "p"; break;
    case 52: return "q"; break;
    case 53: return "r"; break;
    case 54: return "s"; break;
    case 55: return "t"; break;
    case 56: return "u"; break;
    case 57: return "v"; break;
    case 58: return "w"; break;
    case 59: return "x"; break;
    case 60: return "y"; break;
    case 61: return "z"; break;
    }
