entityMapping = {
    # --- TirNaNog ---
    'fence01': 'o_fence01',
    'fence02': 'o_fence02',
    'fence03': 'o_fence03',
    'fence04': 'o_fence04',
    'fence05': 'o_fence05',
    'fence06': 'o_fence06',
    'fence07': 'o_fence07',
    'fence08': 'o_fence08',
    'fence09': 'o_fence09',
    'fence10': 'o_fence10',
    'fence13': 'o_fence13',
    'fence14': 'o_fence14',
    'fence15': 'o_fence15',

    # --- Normal and Infested Factory ---
    'brainshroom_column01': 'o_brainshroom_column01',
    'brainshroom_giant01': 'o_brainshroom_giant01',
    'brainshroom_large01': 'o_brainshroom_large01',
    'brainshroom_small01': 'o_brainshroom_small01',
    'brainstalk01': 'o_brainstalks01',
    'apparatus_factory_gooped01': 'o_apparatus_factory_gooped01',
    'crate_factory_gooped01': 'o_crate_factory_gooped01',
    'mill_gooped01': 'o_mill_gooped01',
    'mill01': 'o_mill01',
    'shelves_gooped01': 'o_shelves_gooped01',
    'tank_factory_large_gooped01': 'o_tank_factory_large_gooped01',
    'tank_factory_large01': 'o_tank_factory_large01',
    'tank_factory_medium_gooped01': 'o_tank_factory_medium_gooped01',
    'tank_factory_medium01': 'o_tank_factory_medium01',
    'tank_factory_small_gooped01': 'o_tank_factory_small_gooped01',
    

    # --- Mines ---
    'mines_pole01': 'o_mines_pole01',
    'mines_pole02': 'o_mines_pole02',
    'mines_fence01': 'o_mines_fence01',
    'mines_fence02': 'o_mines_fence02',
    'mines_fence03': 'o_mines_fence03',
    'mines_fence04': 'o_mines_fence04',
    'cart_mine_empty01': 'o_cart_mine_empty01',
    'cart_mine_full01': 'o_cart_mine_full01',

    'fridge01': 'o_fridge01',
    'tire01': 'o_tire_laying01',
    'car01': 'o_car01',
    'cart_shopping01': 'o_cart_shopping01',	
    'hoop1': 'o_hoop01',
    'hoop02': 'o_hoop02',
	
    'machine_gauges_left01': 'o_machine_gauges_left01',
    'machine_levers_right01': 'o_machine_levers_right01',
    'machine_monitor_left01': 'o_machine_monitor_left01',
    'machine_monitor_right01': 'o_machine_monitor_right01',
	
    'tank_ll_cooling_dualpipe01': 'o_tank_ll_cooling_dualpipe01',
    'tank_ll_cooling_dualpipe02': 'o_tank_ll_cooling_dualpipe02',
    'tank_ll_cooling01': 'o_tank_ll_cooling01',
    'tank_ll_holding01': 'o_tank_ll_holding01',
    'tank_ll_holding02': 'o_tank_ll_holding02',
    'tank_ll_processing01': 'o_tank_ll_processing01',
    'machine_coolingunit01': 'o_machine_coolingunit01',
    'water_tank01': 'o_water_tank01',
	
    'apple_green01': 'o_apple_green01',
    'apple_green02': 'o_apple_green02',
    'apple_red01': 'o_apple_red01',
    'apple_red02': 'o_applered02',
    'barrel_wood01': 'o_barrel_wood01',
    'boxes_pile01': 'o_boxes_pile01',
    'boxes_single01': 'o_boxes_single01',
    'crate_wooden_open01': 'o_crate_wooden_open01',	
    'crate_wooden01': 'o_crate_wooden01',
    'crate_wooden04': 'o_crate_wooden04',
    'crate_wooden_stack01': 'o_crate_wooden_stack01',
    'crate_wooden_stack02': 'o_crate_wooden_stack02',
    'crate_coal01': 'o_crate_coal01',
    'drum01': 'o_drum01',
    'drum_open01': 'o_drum_open01',
	
    'statue_cuchu01': 'o_statue_cuchu01',
    'statue_cuchu02': 'o_statue_cuchu02',
    'outhouse01': 'o_outhouse01',
    'hut01': 'o_hut01',
    'hut02': 'o_hut02',
    'hut03': 'o_hut03',
    'hut04': 'o_hut04',
    'hut05': 'o_hut05',

    'outcrop_red01':'o_outcrop_red01',
    'outcrop_red02':'o_outcrop_red02',

    # --- Trigal ---
    'oo_wheat01': 'o_wheat01',

    # --- Swamp ---
    'stupa_01': 'o_stupa01',
    'stupa_02': 'o_stupa02',
    'stupa_03': 'o_stupa03',
    'stupa_04': 'o_stupa04',
    'stupa_water01': 'o_stupa_water01',
    'stupa_water02': 'o_stupa_water02',
    'stupa_water03': 'o_stupa_water03',
    'stupa_water04': 'o_stupa_water04',
	
	'air_column_01': 'o_air_column01',
    'air_column_02': 'o_air_column02',
    'air_column_03': 'o_air_column03',
    'wall_broken01': 'o_wall_broken01',
    'wall_broken02': 'o_wall_broken02',
    'wall_broken03': 'o_wall_broken03',
    'wall_broken04': 'o_wall_broken04',
    'wall_broken05': 'o_wall_broken05',
    'wall_broken06': 'o_wall_broken06',
    'wall_broken07': 'o_wall_broken07',
    'wall_broken08': 'o_wall_broken08',
    'wall_broken09': 'o_wall_broken09',
    'wall_broken10': 'o_wall_broken10',
	'wall_broken11': 'o_wall_broken11',
	'wall_broken12': 'o_wall_broken12',
	'wall_broken13': 'o_wall_broken13',
	'wall_broken14': 'o_wall_broken14',
	'wall_broken15': 'o_wall_broken15',
	'wall_broken16': 'o_wall_broken16',
	'wall_broken17': 'o_wall_broken17',
	
	'rock01': 'o_rock01',
    'rock02': 'o_rock02',
	'rock_snow01': 'o_rock_snow01',
	'rock_snow02': 'o_rock_snow02',
    'rock_water01': 'o_rock_water01',
    'rock_water02': 'o_rock_water02',
    'rock_dry_medium01': 'o_rock_dry_medium01',
    'rock_dry_large01': 'o_rock_dry_large01',
	'crystal_large01': 'o_crystal_large01',
    'crystal_small01': 'o_crystal_small01',
    'crystal_small02': 'o_crystal_small02',
    'outcrop_right01': 'o_outcrop_right01',
    'outcrop_right02': 'o_outcrop_right02',
    'outcrop_right03': 'o_outcrop_right03',
	'outcrop_left01': 'o_outcrop_left01',
    'outcrop_left02': 'o_outcrop_left02',
	'outcrop_left_hefty01': 'o_outcrop_left_hefty01',
	'outcrop_left_hefty02': 'o_outcrop_left_hefty02',
	'outcrop_right_hefty01': 'o_outcrop_right_hefty01',
	'outcrop_right_hefty02': 'o_outcrop_right_hefty02',
	'crag_dry01': 'o_crag_dry01',
    'crag_dry02': 'o_crag_dry02',
    'crag_dry03': 'o_crag_dry03',
    'crag_dry04': 'o_crag_dry04',
    'crag_dry05': 'o_crag_dry05',
    'crag_dry06': 'o_crag_dry06',
    'crag_dry07': 'o_crag_dry07',
    'crag_dry08': 'o_crag_dry08',
    'crag_dry09': 'o_crag_dry09',
    'crag_dry10': 'o_crag_dry10',
    'crag_snow01': 'o_crag_snow01',
    'crag_snow02': 'o_crag_snow02',
    'crag_snow03': 'o_crag_snow03',
    'crag_snow04': 'o_crag_snow04',
	
	'tree_dead03': 'o_tree_dead03',
    'tree_dead04': 'o_tree_dead04',
    'tree_dead05': 'o_tree_dead05',
	'tree_dead06': 'o_tree_dead06',
	'tree_dead07': 'o_tree_dead07',
	'tree_live01': 'o_tree_live01',
	'tree_live_dummy01': 'o_tree_live_dummy01',
	'tree_live_small01': 'o_tree_live_small01',
	'tree_live_tiny01': 'o_tree_live_tiny01',
	'tree_snow01': 'o_tree_snow01',
    'tree_snow02': 'o_tree_snow02',
	'tree_stump02': 'o_tree_stump02',
    'tree_stump03': 'o_tree_stump03',
    'tree_stump04': 'o_tree_stump04',
	'tree_trunk_floating02': 'o_tree_trunk_floating02',
	'tree_trunk_moss02': 'o_tree_trunk_moss02',
	'tree_trunk02': 'o_tree_trunk02',	
    'tree_dead_water01': 'o_tree_dead_water01',
    'tree_dead_water02': 'o_tree_dead_water02',
	'tree_stump_water01': 'o_tree_stump_water01',
    'tree_stump_water02': 'o_tree_stump_water02',	
	'tree_stump_snow01': 'o_tree_stump_snow01',
	'tree_vrw01': 'o_vrw_tree',
	
	'bush01': 'o_bush01',
    'bush02': 'o_bush02',
	'moss_snow01': 'o_moss_snow01',
    'grass_dry01': 'o_grass_dry01',
	'snow_grass01': 'o_grass_snow01',
	'swamp_grass01': 'o_grass01',
	'swamp_grass_dummy01': 'o_grass_dummy01',
	'swamp_cattail01': 'o_cattail01',
	'swamp_cattail_dummy01': 'o_cattail_dummy01',
	'cabbage01': 'o_cabbage01',
	'carrot01': 'o_carrot01',
    'onion01': 'o_onion01',
	'fary_tree01': 'o_tree_fary01',
	'fary_tree02': 'o_tree_fary02',
	'fary_tree03': 'o_tree_fary03',
	'fary_tree04': 'o_tree_fary04',
    
	'pipe_fence_diagonal01': 'o_pipefence_diagonal01',
	'pipe_fence_diagonal02': 'o_pipefence_diagonal02',
	'pipe_fence_vertical01': 'o_pipefence_vertical01',
	'pipe_fence_vertical02': 'o_pipefence_vertical02',
	'pipe_fence_horizontal01': 'o_pipefence_horizontal01',
	'pipe_fence_horizontal02': 'o_pipefence_horizontal02',
	'pipe_fence_mess01': 'o_pipefence_mess01',
	'wasteland_pile01': 'o_junkpile_small01',
	'wasteland_pile02': 'o_junkpile_average01',
	'wasteland_pile03': 'o_junkpile_large01',
	'wasteland_pile04': 'o_junkpile_huge01',
	'barrel_big_fallen01': 'o_barrel_big_fallen01',
	'barrel_big_fallen02': 'o_barrel_big_fallen02',
	'barrel_big01': 'o_barrel_big01',	
	'broken_monitor01': 'o_broken_monitor01',
	'broken_toilet01': 'o_broken_toilet01',
	'broken_tv01': 'o_broken_tv01',
	'trashbag01': 'o_trash_bag01',
	'crucified_goons01': 'o_crucified_goon01',
	'spinner01': 'o_vrw_spin',

    'chair_accent_back01': 'o_chair_accent_back01',
    'chair_accent_full_front01': 'o_chair_accent_full_front01',
    'chair_accent_full_left01': 'o_chair_accent_full_left01',
    'chair_accent_full_right01': 'o_chair_accent_full_right01',
    'chair_accent_janky_back01': 'o_chair_accent_janky_back01',
    'chair_accent_janky_front01': 'o_chair_accent_janky_front01',
    'chair_stool_darkwood01': 'o_chair_stool_darkwood01',
    'chair_stool_metal01': 'o_chair_stool_metal01',
    'chair_stool_wood01': 'o_chair_stool_wood01',
    'chair_wood_back01': 'o_chair_wood_back01',
    'chair_wood_front01': 'o_chair_wood_front01',
    'chair_wood_left01': 'o_chair_wood_left01',
    'chair_wood_right01': 'o_chair_wood_right01',
    'computer_desk_back01': 'o_computer_desk_back01',
    'computer_desk_front01': 'o_computer_desk_front01',
    'couch_full_back01': 'o_couch_full_back01',
    'couch_full_front01': 'o_couch_full_front01',
    'couch_full_left01': 'o_couch_full_left01',
    'couch_full_right01': 'o_couch_full_right01',
    'couch_janky_back01': 'o_couch_janky_back01',
    'couch_janky_front01': 'o_couch_janky_front01',
    'couch_janky_left01': 'o_couch_janky_left01',
    'couch_janky_right01': 'o_couch_janky_right01',
	
    'table_circle_setting01': 'o_table_circle_setting01',
    'table_circle_wood01': 'o_table_circle_wood01',
    'table_dark_horz01': 'o_table_dark_horz01',
    'table_dark_vert01': 'o_table_dark_vert01',
    'table_dinner_horz01': 'o_table_dinner_horz01',
    'table_dinner_vert01': 'o_table_dinner_vert01',
    'table_square_cloth01': 'o_table_square_cloth01',
    'table_square_darkwood01': 'o_table_square_darkwood01',
    'table_square_largewood01': 'o_table_square_largewood01',
    'table_square_lightwood01': 'o_table_square_lightwood01',
    'table_worn_horz01': 'o_table_worn_horz01',
    'table_worn_vert01': 'o_table_worn_vert01',
    'table_counter01': 'o_table_counter01',
    'table_counter02': 'o_table_counter02',
    'table_counter03': 'o_table_counter03',
    'table_counter04': 'o_table_counter04',
    'table_counter05': 'o_table_counter05',
    'table_counter06': 'o_table_counter06',
    'table_counter07': 'o_table_counter07',
    'table_counter08': 'o_table_counter08',
	
    'bed_made_wood01': 'o_bed_made_wood01',
	'bed_mattress_bare01': 'o_bed_mattress_bare01',
    'bed_hospital01': 'o_hospitalBed01',    
    'cabinet_worn_front01': 'o_cabinet_worn_front01',
    'lamp_standing01': 'o_lamp_standing01',
    'radiator_left01': 'o_radiator_left01',
    'trashcan_empty01': 'o_trashcan_empty01',
    'trashcan_full01': 'o_trashcan_full01',
	
	'sink01': 'o_sink01',
    'tv_full_back01': 'o_tv_full_back01',
    'tv_full_front01': 'o_tv_full_front01',
	
	'biotek_alarm01': 'o_biotek_alarm01',	
	'biotek_gizmo01': 'o_biotek_gizmo01',
	'biotek_biotube01': 'o_biotek_biotube01',
	'biotek_biotube02': 'o_biotek_biotube02',
	'biotek_biotube03': 'o_biotek_biotube03',
	'biotek_biotube04': 'o_biotek_biotube04',
	'biotek_biotube05': 'o_biotek_biotube05',
	'biotek_computer01': 'o_biotek_computer01',
	'biotek_cybercounter01': 'o_biotek_cybercounter01',
	'biotek_fiend01': 'o_biotek_fiend01',
	'biotek_generator01': 'o_biotek_generator01',
	'biotek_generator02': 'o_biotek_generator02',
	'biotek_generator03': 'o_biotek_generator03',
	'biotek_gizmo01': 'o_biotek_gizmo01',
	'biotek_locker01': 'o_biotek_locker01',
	'biotek_hardware01': 'o_biotek_hardware01',
	'biotek_hardware02': 'o_biotek_hardware02',
	'biotek_hardware03': 'o_biotek_hardware03',
	'biotek_monitor01': 'o_biotek_monitor01',
	'biotek_slendertube01': 'o_biotek_slendertube01',
	'biotek_superCPU01': 'o_biotek_superCPU01',
	'biotek_table01': 'o_biotek_table01',
	
    'solid_tri1': 'o_solid_tri1',
    'solid_tri2': 'o_solid_tri2',
    'solid_tri3': 'o_solid_tri3',
    'solid_tri4': 'o_solid_tri4',
    'semisolid_tri1': 'o_semisolid_tri1',
    'semisolid_tri2': 'o_semisolid_tri2',
    'semisolid_tri3': 'o_semisolid_tri3',
    'semisolid_tri4': 'o_semisolid_tri4',
    'solid_circle': 'o_solid_circle',
    'semisolid_circle': 'o_semisolid_circle'
}

