# List rooms as [.oep file name, .oel file name, GM:S room name]

roomMapping = [  
# AI Ruins 
#['barkley2_mastermap02', 'airuins/map_air_boss01', 						'r_air_boss01'],
#['barkley2_mastermap02', 'airuins/map_air_cloister01', 					'r_air_cloister01'],
#['barkley2_mastermap02', 'airuins/map_air_cloisterLobby01', 			'r_air_cloisterLobby01'],
#['barkley2_mastermap02', 'airuins/map_air_corridor01', 					'r_air_corridor01'],
#['barkley2_mastermap02', 'airuins/map_air_entrance01', 					'r_air_entrance01'],
#['barkley2_mastermap02', 'airuins/map_air_filler01', 					'r_air_filler01'],
#['barkley2_mastermap02', 'airuins/map_air_finalgun01', 					'r_air_finalgun01'],
#['barkley2_mastermap02', 'airuins/map_air_longRoom01', 					'r_air_longRoom01'],
#['barkley2_mastermap02', 'airuins/map_air_respawn01', 					'r_air_respawn01'],
#['barkley2_mastermap02', 'airuins/map_air_respawnCorridor01', 			'r_air_respawnCorridor01'],
#['barkley2_mastermap02', 'airuins/map_air_scannerFirst01', 				'r_air_scannerFirst01'],
#['barkley2_mastermap02', 'airuins/map_air_throneRoom01', 				'r_air_throneRoom01'],
#
## Al Akihabara
#['barkley2_mastermap02', 'swamp/alakihabara/map_dz2_alakihabara01', 'r_dz2_alakihabara'],
#['barkley2_mastermap02', 'swamp/alakihabara/map_dz2_zalatarfoyer01', 'r_dz2_zalatarfoyer01'],
#['barkley2_mastermap02', 'swamp/alakihabara/map_dz2_zalatarroom01', 'r_dz2_zalatarroom01'],
#
## Biotek 
#['barkley2_mastermap02', 'factory/biotek/map_fct_biotek_dataRoom01', 		'r_fct_biotek_dataRoom01'],
#['barkley2_mastermap02', 'factory/biotek/map_fct_biotek_dataRoom02', 		'r_fct_biotek_dataRoom02'],
#['barkley2_mastermap02', 'factory/biotek/map_fct_biotek_incubationRoom01', 'r_fct_biotek_incubationRoom01'],
#['barkley2_mastermap02', 'factory/biotek/map_fct_biotek_kingRoom01', 		'r_fct_biotek_kingRoom01'],
#['barkley2_mastermap02', 'factory/biotek/map_fct_biotek_passageLeft01', 	'r_fct_biotek_passageLeft01'],
#['barkley2_mastermap02', 'factory/biotek/map_fct_biotek_passageRight01', 	'r_fct_biotek_passageRight01'],
#['barkley2_mastermap02', 'factory/biotek/map_fct_biotek_plantRoom01', 		'r_fct_biotek_plantRoom01'],
#['barkley2_mastermap02', 'factory/biotek/map_fct_biotek_sectionA01', 		'r_fct_biotek_sectionA01'],
#['barkley2_mastermap02', 'factory/biotek/map_fct_biotek_sectionB01', 		'r_fct_biotek_sectionB01'],
#['barkley2_mastermap02', 'factory/biotek/map_fct_biotek_staffRoom01', 		'r_fct_biotek_staffRoom01'],
#
## Brain City Towers
#['barkley2_mastermap02', 'braincity/map_bct_tower01', 'r_bct_tower01'],
#['barkley2_mastermap02', 'braincity/map_bct_tower02', 'r_bct_tower02'],
#['barkley2_mastermap02', 'braincity/map_bct_tower03', 'r_bct_tower03'],
#['barkley2_mastermap02', 'braincity/map_bct_tower04', 'r_bct_tower04'],
#['barkley2_mastermap02', 'braincity/map_bct_tower05', 'r_bct_tower05'],
#['barkley2_mastermap02', 'braincity/map_bct_tower06', 'r_bct_tower06'],
#['barkley2_mastermap02', 'braincity/map_bct_tower07', 'r_bct_tower07'],

# Cuchu's Lair 
['barkley2_mastermap02', 'cuchulair/map_chu_arena01', 				'r_chu_arena01'],
['barkley2_mastermap02', 'cuchulair/map_chu_conference01',			'r_chu_conference01'],
['barkley2_mastermap02', 'cuchulair/map_chu_corridor01', 			'r_chu_corridor01'], 
['barkley2_mastermap02', 'cuchulair/map_chu_entrance02', 			'r_chu_entrance02'],
['barkley2_mastermap02', 'cuchulair/map_chu_minotaur01', 			'r_chu_minotaur01'], 
['barkley2_mastermap02', 'cuchulair/map_chu_pool01', 				'r_chu_pool01'], 
['barkley2_mastermap02', 'cuchulair/map_chu_shock01', 				'r_chu_shock01'], 
['barkley2_mastermap02', 'cuchulair/map_chu_tdwarf01', 				'r_chu_tdwarf01'], 
['barkley2_mastermap02', 'cuchulair/map_chu_walk01', 				'r_chu_walk01'], 
['barkley2_mastermap02', 'cuchulair/map_chu_warroom01', 			'r_chu_warroom01'], 
['barkley2_mastermap02', 'cuchulair/map_chu_zenith01', 				'r_chu_zenith01'], 
 
# Eastelands maps	
#['barkley2_mastermap02', 'eastelands/map_est_caveMoney01', 			'r_est_caveMoney01'],
#['barkley2_mastermap02', 'eastelands/map_est_caveShop01', 			'r_est_caveShop01'],
#['barkley2_mastermap02', 'eastelands/map_est_cgremArena01', 		'r_est_cgremArena01'],
#['barkley2_mastermap02', 'eastelands/map_est_cgremPath01', 			'r_est_cgremPath01'],
#['barkley2_mastermap02', 'eastelands/map_est_cgremVillage01', 		'r_est_cgremVillage01'],	
#['barkley2_mastermap02', 'eastelands/map_est_difficultyFork01', 	'r_est_difficultyFork01'],
#['barkley2_mastermap02', 'eastelands/map_est_easternPaths01', 		'r_est_easternPaths01'],
#['barkley2_mastermap02', 'eastelands/map_est_factoryChicane01', 	'r_est_factoryChicane01'],			
#['barkley2_mastermap02', 'eastelands/map_est_industrialPlaza01', 	'r_est_industrialPlaza01'],	
#['barkley2_mastermap02', 'eastelands/map_est_industrialRock01', 	'r_est_industrialRock01'],
#['barkley2_mastermap02', 'eastelands/map_est_industrialZone01', 	'r_est_industrialZone01'],	
#['barkley2_mastermap02', 'eastelands/map_est_junkworms01', 			'r_est_junkworms01'],
#['barkley2_mastermap02', 'eastelands/map_est_mountainBase01', 		'r_est_mountainBase01'],	
#['barkley2_mastermap02', 'eastelands/map_est_mountainPath01', 		'r_est_mountainPath01'],
#['barkley2_mastermap02', 'eastelands/map_est_pythagoras01', 		'r_est_pythagoras01'],
#['barkley2_mastermap02', 'eastelands/map_est_snoozer01', 			'r_est_snoozer01'],	
#['barkley2_mastermap02', 'eastelands/map_est_southBeach01',	 		'r_est_southBeach01'],
#['barkley2_mastermap02', 'eastelands/map_est_southDeadend01', 		'r_est_southDeadend01'],
#['barkley2_mastermap02', 'eastelands/map_est_southScam01',	 		'r_est_southScam01'],
#['barkley2_mastermap02', 'eastelands/map_est_swampZigzag01', 		'r_est_swampZigzag01'],	
#['barkley2_mastermap02', 'eastelands/map_est_tnnRespawn01', 		'r_est_tnnRespawn01'],	
#['barkley2_mastermap02', 'eastelands/map_est_turretGauntlet01', 	'r_est_turretGauntlet01'],
# 
## Factory, Outdoors
#['barkley2_mastermap02', 'factory/map_fct_factoryBackyard01', 		'r_fct_factoryBackyard01'],
#['barkley2_mastermap02', 'factory/map_fct_factoryOutpost01', 		'r_fct_factoryOutpost01'],		
#['barkley2_mastermap02', 'factory/map_fct_factoryParking01', 		'r_fct_factoryParking01'],
#['barkley2_mastermap02', 'factory/map_fct_factoryStorage01', 		'r_fct_factoryStorage01'],
#
## Factory, Floor ONE
#['barkley2_mastermap02', 'factory/map_fct_arena01', 	    'r_fct_arena01'],
#['barkley2_mastermap02', 'factory/map_fct_assembly02', 	    'r_fct_assembly01'],
#['barkley2_mastermap02', 'factory/map_fct_bigRoom01', 	    'r_fct_bigRoom01'],
#['barkley2_mastermap02', 'factory/map_fct_cafeteria01',     'r_fct_cafeteria01'],
#['barkley2_mastermap02', 'factory/map_fct_control01', 	    'r_fct_control01'],
#['barkley2_mastermap02', 'factory/map_fct_corner01', 	    'r_fct_corner01'],
#['barkley2_mastermap02', 'factory/map_fct_corridor01', 	    'r_fct_corridor01'],	
#['barkley2_mastermap02', 'factory/map_fct_gizmo01', 	    'r_fct_gizmo01'],
#['barkley2_mastermap02', 'factory/map_fct_kitchen01', 	    'r_fct_kitchen01'],
#['barkley2_mastermap02', 'factory/map_fct_loading01', 	    'r_fct_loading01'],
#['barkley2_mastermap02', 'factory/map_fct_lobby01', 	    'r_fct_lobby01'],
#['barkley2_mastermap02', 'factory/map_fct_office01', 	    'r_fct_office01'],
#['barkley2_mastermap02', 'factory/map_fct_respawn01', 	    'r_fct_respawn01'],
#['barkley2_mastermap02', 'factory/map_fct_return01', 	    'r_fct_return01'],		
#['barkley2_mastermap02', 'factory/map_fct_storage01', 	    'r_fct_storage01'],
#
## Factory, Floor TWO
#['barkley2_mastermap02', 'factory/map_fct_accessHall01',    'r_fct_accessHall01'],
#['barkley2_mastermap02', 'factory/map_fct_eggRooms01', 	    'r_fct_eggRooms01'],
#['barkley2_mastermap02', 'factory/map_fct_eggDrone01', 	    'r_fct_eggDrone01'],
#['barkley2_mastermap02', 'factory/map_fct_elevator01',      'r_fct_elevator01'],
#['barkley2_mastermap02', 'factory/map_fct_tutorialZone01',  'r_fct_tutorialZone01'],
#['barkley2_mastermap02', 'factory/map_fct_reroute01',       'r_fct_reroute01'],
#
## Factory, Floor TWO, POST-GOOPAGE
#['barkley2_mastermap02', 'factory/map_fct_accessHallGooped01',    'r_fct_accessHallGooped01'],
#['barkley2_mastermap02', 'factory/map_fct_elevator2nd01',         'r_fct_elevator2nd01'],
#['barkley2_mastermap02', 'factory/map_fct_tutorialZoneAfter01',   'r_fct_tutorialZoneAfter01'],
#['barkley2_mastermap02', 'factory/map_fct_rerouteGooped01',       'r_fct_rerouteGooped01'],
#
## Fary Forest
#['barkley2_mastermap02', 'fary_forest/map_far_doppel01',  			'r_far_doppel01'],
#['barkley2_mastermap02', 'fary_forest/map_far_front01', 	 		'r_far_front01'],
#['barkley2_mastermap02', 'fary_forest/map_far_nexus01', 	 		'r_far_nexus01'],
#['barkley2_mastermap02', 'fary_forest/map_far_northCorner01', 		'r_far_northCorner01'],
#['barkley2_mastermap02', 'fary_forest/map_far_southCorner01',  	 	'r_far_southCorner01'],
#['barkley2_mastermap02', 'fary_forest/map_far_southHill01', 		'r_far_southHill01'],
#['barkley2_mastermap02', 'fary_forest/map_far_westEnd01', 			'r_far_westEnd01'],
#
## Fishing 
#['barkley2_mastermap02', 'fishing/map_fis_ice01', 			'r_fis_ice01'],
#['barkley2_mastermap02', 'fishing/map_fis_mountain01', 		'r_fis_mountain01'],
#['barkley2_mastermap02', 'fishing/map_fis_nexus01', 		'r_fis_nexus01'],
#['barkley2_mastermap02', 'fishing/map_fis_sewer01', 		'r_fis_sewer01'],
#['barkley2_mastermap02', 'fishing/map_fis_sewer02', 		'r_fis_sewer02'],
#['barkley2_mastermap02', 'fishing/map_fis_swamps01', 		'r_fis_swamps01'],
#['barkley2_mastermap02', 'fishing/map_fis_undersewer01', 	'r_fis_undersewer01'],
#['barkley2_mastermap02', 'fishing/map_fis_wasteland01', 	'r_fis_wasteland01'],
#
## Frigid Outskirts
#['barkley2_mastermap02', 'iceland/map_ice_dojoIndoors01', 		'r_ice_dojoIndoors01'],
#['barkley2_mastermap02', 'iceland/map_ice_dojoOutdoors01', 		'r_ice_dojoOutdoors01'],
#['barkley2_mastermap02', 'iceland/map_ice_dojoPond01', 			'r_ice_dojoPond01'],
#['barkley2_mastermap02', 'iceland/map_ice_outskirtsA1_01', 		'r_ice_outskirtsA1_01'],
#['barkley2_mastermap02', 'iceland/map_ice_outskirtsA2_01', 		'r_ice_outskirtsA2_01'],
#['barkley2_mastermap02', 'iceland/map_ice_outskirtsA3_01', 		'r_ice_outskirtsA3_01'],
#['barkley2_mastermap02', 'iceland/map_ice_outskirtsB1_01', 		'r_ice_outskirtsB1_01'],
#['barkley2_mastermap02', 'iceland/map_ice_outskirtsB2_01', 		'r_ice_outskirtsB2_01'],
#['barkley2_mastermap02', 'iceland/map_ice_outskirtsB3_01', 		'r_ice_outskirtsB3_01'],
#['barkley2_mastermap02', 'iceland/map_ice_outskirtsC1_01', 		'r_ice_outskirtsC1_01'],
#['barkley2_mastermap02', 'iceland/map_ice_outskirtsC2_01', 		'r_ice_outskirtsC2_01'],
#['barkley2_mastermap02', 'iceland/map_ice_outskirtsC3_01', 		'r_ice_outskirtsC3_01'],
#['barkley2_mastermap02', 'iceland/map_ice_respawn01', 			'r_ice_respawn01'],
#['barkley2_mastermap02', 'iceland/map_ice_treasure01', 			'r_ice_treasure01'],
# 
## Hoosegow
#['barkley2_mastermap02', 'prison/map_pri_prisonCourt01', 		'r_pri_prisonCourt01'],	
#['barkley2_mastermap02', 'prison/map_pri_prisonGate01', 		'r_pri_prisonGate01'],	
#['barkley2_mastermap02', 'prison/map_pri_prisonInside01', 		'r_pri_prisonInside01'],	
#['barkley2_mastermap02', 'prison/map_pri_prisonProcessing01', 	'r_pri_prisonProcessing01'],
# 
## Mines
#['barkley2_mastermap02', 'mines01/map_min_baseCampAlpha01', 	'r_min_baseCampAlpha01'],
#['barkley2_mastermap02', 'mines01/map_min_baseCampBeta01', 		'r_min_baseCampBeta01'],	
#['barkley2_mastermap02', 'mines01/map_min_constantine01', 		'r_min_constantine01'],
#['barkley2_mastermap02', 'mines01/map_min_eastPit01', 			'r_min_eastPit01'],
#['barkley2_mastermap02', 'mines01/map_min_entrance01', 		    'r_min_entrance01'],
#['barkley2_mastermap02', 'mines01/map_min_jeanmarcPit01', 		'r_min_jeanmarcPit01'],
#['barkley2_mastermap02', 'mines01/map_min_junction01', 			'r_min_junction01'],
#['barkley2_mastermap02', 'mines01/map_min_kaleviCave01', 		'r_min_kaleviCave01'],			
#['barkley2_mastermap02', 'mines01/map_min_respawn01', 			'r_min_respawn01'],
#['barkley2_mastermap02', 'mines01/map_min_secret01', 			'r_min_secret01'],
# 
## Mountain Pass AKA Gilbert's Peak (arranged in "altitude order")
#['barkley2_mastermap02', 'mountainpass/map_pea_ledgeBottom01',  	 	'r_pea_ledgeBottom01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_caveRespawnBase01',  	'r_pea_caveRespawnBase01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_pond01',  	 			'r_pea_pond01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_ladderBase01',	        'r_pea_ladderBase01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_riverOverpass01',	 	'r_pea_riverOverpass01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_caveBottom01',  	 	 	'r_pea_caveBottom01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_caveRebel01',             'r_pea_caveRebel01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_caveBottomLadder01',      'r_pea_caveBottomLadder01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_caveCenter01',  	         'r_pea_caveCenter01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_curve01',  	         	'r_pea_curve01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_divingPlatform01',        'r_pea_divingPlatform01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_caveMidwayLadder01',      'r_pea_caveMidwayLadder01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_caveMidwayConnection01',  'r_pea_caveMidwayConnection01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_passMidway01',	         'r_pea_passMidway01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_ladderMidway01',	         'r_pea_ladderMidway01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_harpyCorner01',           'r_pea_harpyCorner01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_harpyNest01',             'r_pea_harpyNest01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_duergarCamp01',           'r_pea_duergarCamp01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_ledgeCenter01',  	 	'r_pea_ledgeCenter01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_caveTop01',  	 	 	'r_pea_caveTop01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_caveDivingAccess01',     'r_pea_caveDivingAccess01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_caveTopExit01',  	 	'r_pea_caveTopExit01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_snowEntrance01',         'r_pea_snowEntrance01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_snowCanyon01',           'r_pea_snowCanyon01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_snowLedge01',           	'r_pea_snowLedge01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_snowHotspring01',        'r_pea_snowHotspring01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_snowForest01',           'r_pea_snowForest01'],
#['barkley2_mastermap02', 'mountainpass/map_pea_snowTop01',           	'r_pea_snowTop01'],	
# 
## Sewers FLOOR 1		
#['barkley2_mastermap02', 'sewers/map_sw1_baldomero01', 			'r_sw1_baldomero01'],
#['barkley2_mastermap02', 'sewers/map_sw1_center01', 			'r_sw1_center01'],
#['barkley2_mastermap02', 'sewers/map_sw1_closet01', 			'r_sw1_closet01'],
#['barkley2_mastermap02', 'sewers/map_sw1_crossroads01', 		'r_sw1_crossroads01'],
#['barkley2_mastermap02', 'sewers/map_sw1_darkestAlley01', 		'r_sw1_darkestAlley01'],
#['barkley2_mastermap02', 'sewers/map_sw1_descent01', 			'r_sw1_descent01'],
#['barkley2_mastermap02', 'sewers/map_sw1_eastEdge01', 			'r_sw1_eastEdge01'],
#['barkley2_mastermap02', 'sewers/map_sw1_elemental01', 			'r_sw1_elemental01'],
#['barkley2_mastermap02', 'sewers/map_sw1_end01', 				'r_sw1_end01'],
#['barkley2_mastermap02', 'sewers/map_sw1_fishersCreek01', 		'r_sw1_fishersCreek01'],	
#['barkley2_mastermap02', 'sewers/map_sw1_floor2Access01', 		'r_sw1_floor2Access01'],
#['barkley2_mastermap02', 'sewers/map_sw1_foyer01', 				'r_sw1_foyer01'],	
#['barkley2_mastermap02', 'sewers/map_sw1_gap01', 				'r_sw1_gap01'],
#['barkley2_mastermap02', 'sewers/map_sw1_gutterGate01', 		'r_sw1_gutterGate01'],
#['barkley2_mastermap02', 'sewers/map_sw1_joad01', 				'r_sw1_joad01'],
#['barkley2_mastermap02', 'sewers/map_sw1_longWays01', 			'r_sw1_longWays01'],
#['barkley2_mastermap02', 'sewers/map_sw1_manholeEast01', 		'r_sw1_manholeEast01'],
#['barkley2_mastermap02', 'sewers/map_sw1_manholeWest01', 		'r_sw1_manholeWest01'],
#['barkley2_mastermap02', 'sewers/map_sw1_plantation01', 		'r_sw1_plantation02'],
#['barkley2_mastermap02', 'sewers/map_sw1_pool01', 				'r_sw1_pool01'],
#['barkley2_mastermap02', 'sewers/map_sw1_rathell01', 			'r_sw1_rathell01'],
#['barkley2_mastermap02', 'sewers/map_sw1_respawn01', 			'r_sw1_respawn01'],
#['barkley2_mastermap02', 'sewers/map_sw1_secret01', 			'r_sw1_secret01'],
#['barkley2_mastermap02', 'sewers/map_sw1_southEdge01', 			'r_sw1_southEdge01'],
#['barkley2_mastermap02', 'sewers/map_sw1_tnnShortcut01', 		'r_sw1_tnnShortcut01'],
#['barkley2_mastermap02', 'sewers/map_sw1_treasureDwarf01', 		'r_sw1_treasureDwarf01'],
#['barkley2_mastermap02', 'sewers/map_sw1_utility01', 			'r_sw1_utility01'],
#
## Sewers FLOOR 2
#['barkley2_mastermap02', 'sewers/map_sw2_balcony01', 			'r_sw2_balcony01'],
#['barkley2_mastermap02', 'sewers/map_sw2_bridges01', 			'r_sw2_bridges01'],
#['barkley2_mastermap02', 'sewers/map_sw2_crossing01', 			'r_sw2_crossing01'],
#['barkley2_mastermap02', 'sewers/map_sw2_crossroad01', 			'r_sw2_crossroad01'],
#['barkley2_mastermap02', 'sewers/map_sw2_eastExit01', 			'r_sw2_eastExit01'],
#['barkley2_mastermap02', 'sewers/map_sw2_end01', 				'r_sw2_end01'],
#['barkley2_mastermap02', 'sewers/map_sw2_gordo01', 				'r_sw2_gordo01'],
#['barkley2_mastermap02', 'sewers/map_sw2_hermitPass01', 		'r_sw2_hermitPass01'],
#['barkley2_mastermap02', 'sewers/map_sw2_indianRopeTrick01', 	'r_sw2_indianRopeTrick01'],
#['barkley2_mastermap02', 'sewers/map_sw2_looparound01', 		'r_sw2_looparound01'],
#['barkley2_mastermap02', 'sewers/map_sw2_pools01', 				'r_sw2_pools01'],
#['barkley2_mastermap02', 'sewers/map_sw2_respawn01', 			'r_sw2_respawn01'],
#['barkley2_mastermap02', 'sewers/map_sw2_safeRoom01', 			'r_sw2_safeRoom01'],
#['barkley2_mastermap02', 'sewers/map_sw2_sludgeFloor01', 		'r_sw2_sludgeFloor01'],
#['barkley2_mastermap02', 'sewers/map_sw2_start01', 				'r_sw2_start01'],
#['barkley2_mastermap02', 'sewers/map_sw2_steam01', 				'r_sw2_steam01'],
#['barkley2_mastermap02', 'sewers/map_sw2_steam02', 				'r_sw2_steam02'],
#['barkley2_mastermap02', 'sewers/map_sw2_treasureDwarf01', 		'r_sw2_treasureDwarf01'],
#['barkley2_mastermap02', 'sewers/map_sw2_undersewerAccess01', 	'r_sw2_undersewerAccess01'],
#['barkley2_mastermap02', 'sewers/map_sw2_utility01', 			'r_sw2_utility01'],
#	  
## Swamp	
#['barkley2_mastermap02', 'swamp/map_swp_barkleypond01', 		'r_swp_barkleypond01'],    
#['barkley2_mastermap02', 'swamp/map_swp_bcdeadend01', 			'r_swp_bcdeadend01'],
#['barkley2_mastermap02', 'swamp/map_swp_bcentrance01', 			'r_swp_bcentrance01'],
#['barkley2_mastermap02', 'swamp/map_swp_beach01', 				'r_swp_beach01'],    
#['barkley2_mastermap02', 'swamp/map_swp_bogchurch01', 			'r_swp_bogchurch01'],
#['barkley2_mastermap02', 'swamp/map_swp_centralbend01', 		'r_swp_centralbend01'],
#['barkley2_mastermap02', 'swamp/map_swp_corpseLake01', 			'r_swp_corpseLake01'],       
##['barkley2_mastermap02', 'swamp/map_swp_cuchu1_01', 			'r_swp_cuchu1_01'],   
##['barkley2_mastermap02', 'swamp/map_swp_cuchu3_01', 			'r_swp_cuchu3_01'],
##['barkley2_mastermap02', 'swamp/map_swp_cuchu4_01', 			'r_swp_cuchu4_01'],
##['barkley2_mastermap02', 'swamp/map_swp_cuchuelevator01', 		'r_swp_cuchuelevator01'],
#['barkley2_mastermap02', 'swamp/map_swp_duergarencounter01', 	'r_swp_duergarencounter01'],
#['barkley2_mastermap02', 'swamp/map_swp_eastwestcrossroads01', 	'r_swp_eastwestcrossroads01'],
#['barkley2_mastermap02', 'swamp/map_swp_flowerguardian01', 		'r_swp_flowerguardian01'],    	
#['barkley2_mastermap02', 'swamp/map_swp_gamerCorner01', 		'r_swp_gamerCorner01'],	
#['barkley2_mastermap02', 'swamp/map_swp_koboldcamp01', 			'r_swp_koboldcamp01'],
#['barkley2_mastermap02', 'swamp/map_swp_koboldchallenge01', 	'r_swp_koboldchallenge01'],	
#['barkley2_mastermap02', 'swamp/map_swp_longpathrespawn01', 	'r_swp_longpathrespawn01'],	
#['barkley2_mastermap02', 'swamp/map_swp_longpathutility01', 	'r_swp_longpathutility01'],
#['barkley2_mastermap02', 'swamp/map_swp_northruins01', 			'r_swp_northruins01'],    	
#['barkley2_mastermap02', 'swamp/map_swp_quagmire01', 			'r_swp_quagmire01'],	
#['barkley2_mastermap02', 'swamp/map_swp_respawntrash01', 		'r_swp_respawntrash01'],
#['barkley2_mastermap02', 'swamp/map_swp_respawnwater01', 		'r_swp_respawnwater01'],
#['barkley2_mastermap02', 'swamp/map_swp_roundabout01', 			'r_swp_roundabout01'],
#['barkley2_mastermap02', 'swamp/map_swp_runningManArena01', 	'r_swp_runningManArena01'],
#['barkley2_mastermap02', 'swamp/map_swp_runningManBeach01', 	'r_swp_runningManBeach01'],
#['barkley2_mastermap02', 'swamp/map_swp_runningManLobby01', 	'r_swp_runningManLobby01'],
#['barkley2_mastermap02', 'swamp/map_swp_shacklake01', 			'r_swp_shacklake01'],
#['barkley2_mastermap02', 'swamp/map_swp_southPatch01', 			'r_swp_southPatch01'],	
#['barkley2_mastermap02', 'swamp/map_swp_swampRanch01', 			'r_swp_swampRanch01'],	
#['barkley2_mastermap02', 'swamp/map_swp_towerBeach01', 			'r_swp_towerBeach01'],
#['barkley2_mastermap02', 'swamp/map_swp_towerElevator01', 		'r_swp_towerElevator01'],
#['barkley2_mastermap02', 'swamp/map_swp_towerPath01', 			'r_swp_towerPath01'],
#['barkley2_mastermap02', 'swamp/map_swp_towerShortcut01', 		'r_swp_towerShortcut01'],
#['barkley2_mastermap02', 'swamp/map_swp_towerTop01', 			'r_swp_towerTop01'],
#['barkley2_mastermap02', 'swamp/map_swp_utilityonpath01', 		'r_swp_utilityonpath01'],	
#['barkley2_mastermap02', 'swamp/map_swp_waterbowl01', 			'r_swp_waterbowl01'],	
#['barkley2_mastermap02', 'swamp/map_swp_westentrance01', 		'r_swp_westentrance01'],  
#['barkley2_mastermap02', 'swamp/map_swp_westjunction01', 		'r_swp_westjunction01'],  
#['barkley2_mastermap02', 'swamp/map_swp_westpool01', 			'r_swp_westpool01'],
#['barkley2_mastermap02', 'swamp/map_swp_westshortcut01', 		'r_swp_westshortcut01'],
#['barkley2_mastermap02', 'swamp/map_swp_vineglen01', 			'r_swp_vineglen01'],
#
## TirNaNog Outdoors    
#['barkley2_mastermap02', 'tirnanog/map_tnn_bballcourt_transition01', 	'r_tnn_bballcourt_transition01'],
#['barkley2_mastermap02', 'tirnanog/map_tnn_bballcourt01', 				'r_tnn_bballcourt02'],
#['barkley2_mastermap02', 'tirnanog/map_tnn_businessDistrict01', 		'r_tnn_businessDistrict01'],
#['barkley2_mastermap02', 'tirnanog/map_tnn_maingate03', 				'r_tnn_maingate02'],
#['barkley2_mastermap02', 'tirnanog/map_tnn_marketDistrict01', 			'r_tnn_marketDistrict01'],
#['barkley2_mastermap02', 'tirnanog/map_tnn_residentialDistrict01', 	    'r_tnn_residentialDistrict01'],
#['barkley2_mastermap02', 'tirnanog/map_tnn_warehouseDistrict01',		'r_tnn_warehouseDistrict01'],
#
## TirNaNog Interiors
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_backshop01', 			'r_tnn_backshop01'],
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_bballtenement01', 		'r_tnn_bballtenement01'],
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_blockhouse01', 		'r_tnn_blockhouse01'],
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_boardinghouse01', 		'r_tnn_boardinghouse01'],
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_bootybass02', 			'r_tnn_bootybass02'],	
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_clinic01', 			'r_tnn_clinic01'],
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_ghettoofsadness01', 	'r_tnn_ghettoofsadness01'], 
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_ghosthouse01', 		'r_tnn_ghosthouse01'], 
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_giuseppesChurch01', 	'r_tnn_giuseppesChurch01'],
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_gutterHouse01', 		'r_tnn_gutterHouse01'], 
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_kelpstershouse01', 	'r_tnn_kelpstershouse01'],
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_mortgage01', 			'r_tnn_mortgage01'],
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_petshop01', 			'r_tnn_petshop01'],
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_rebelbase03', 			'r_tnn_rebelbase02'],
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_rentcontrolled01', 	'r_tnn_rentcontrolled01'],    
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_warehouse01', 			'r_tnn_warehouse01'],
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_wilmer01', 			'r_tnn_wilmer01'],
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_wilmer02', 			'r_tnn_wilmer02'],
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_vivian02', 			'r_tnn_vivian02'],
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_govMansionFloorOne01',	'r_tnn_govMansionFloorOne01'],
#['barkley2_mastermap02', 'tirnanog/tnn_interiors/map_tnn_govMansionFloorTwo01',	'r_tnn_govMansionFloorTwo01'],
#
## Undersewers
#['barkley2_mastermap02', 'undersewers/map_usw_balcony01',			'r_usw_balcony01'],
#['barkley2_mastermap02', 'undersewers/map_usw_braincityAccess01', 	'r_usw_braincityAccess01'],
#['barkley2_mastermap02', 'undersewers/map_usw_crossroads01',		'r_usw_crossroads01'],
#['barkley2_mastermap02', 'undersewers/map_usw_ditch01',				'r_usw_ditch01'],
#['barkley2_mastermap02', 'undersewers/map_usw_greatHall01',			'r_usw_greatHall01'],
#['barkley2_mastermap02', 'undersewers/map_usw_klatch01',			'r_usw_klatch01'],
#['barkley2_mastermap02', 'undersewers/map_usw_ladderRebel01',		'r_usw_ladderRebel01'],
#['barkley2_mastermap02', 'undersewers/map_usw_ladderCuchu01',		'r_usw_ladderCuchu01'],
#['barkley2_mastermap02', 'undersewers/map_usw_pipeHall01',			'r_usw_pipeHall01'],
#['barkley2_mastermap02', 'undersewers/map_usw_pool01',				'r_usw_pool01'],
#['barkley2_mastermap02', 'undersewers/map_usw_rebelJunction01',		'r_usw_rebelJunction01'],
#['barkley2_mastermap02', 'undersewers/map_usw_ruinsAccess01',		'r_usw_ruinsAccess01'],
#['barkley2_mastermap02', 'undersewers/map_usw_ruinsJunction01', 	'r_usw_ruinsJunction01'],
#['barkley2_mastermap02', 'undersewers/map_usw_ruinsWifi01', 		'r_usw_ruinsWifi01'],
#['barkley2_mastermap02', 'undersewers/map_usw_wastelandAccess01', 	'r_usw_wastelandAccess01'],
#
## Westeland maps 
#['barkley2_mastermap02', 'wasteland/map_wst_caveFary01', 			'r_wst_caveFary01'],	
#['barkley2_mastermap02', 'wasteland/map_wst_donutDomain01', 		'r_wst_donutDomain01'],	
#['barkley2_mastermap02', 'wasteland/map_wst_northCircle01', 		'r_wst_northCircle01'],
#['barkley2_mastermap02', 'wasteland/map_wst_northPassage01', 		'r_wst_northPassage01'],
#['barkley2_mastermap02', 'wasteland/map_wst_northRespawn01', 		'r_wst_northRespawn01'],
#['barkley2_mastermap02', 'wasteland/map_wst_northRuins01', 			'r_wst_northRuins01'],		
#['barkley2_mastermap02', 'wasteland/map_wst_tnnEntrance01', 		'r_wst_tnnEntrance01'],
#['barkley2_mastermap02', 'wasteland/map_wst_wadingRace01', 			'r_wst_wadingRace01'],
#['barkley2_mastermap02', 'wasteland/map_wst_westJunction01', 		'r_wst_westJunction01'],
#['barkley2_mastermap02', 'wasteland/map_wst_westMaze01', 			'r_wst_westMaze01'],
#['barkley2_mastermap02', 'wasteland/map_wst_westOpenGrounds01', 	'r_wst_westOpenGrounds01'],	

# Ys-Kolob Area
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_backalley01',			'r_pdt_backalley01'],
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_dumpster01',			'r_pdt_dumpster01'],
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_eelThrone01',			'r_pdt_eelThrone01'],	
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_elevator01',			'r_pdt_elevator01'],
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_graves01',			'r_pdt_graves01'],
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_italiano01',			'r_pdt_italiano01'],
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_katzenKave01',		'r_pdt_katzenKave01'],
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_katzenKave02',		'r_pdt_katzenKave02'],
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_pitsLobby01',			'r_pdt_pitsLobby1'],		
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_pitsMaze01',			'r_pdt_pitsMaze01'],
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_pitsMiddle01',		'r_pdt_pitsMiddle01'],
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_pitsSouth01',			'r_pdt_pitsSouth01'],
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_political01',			'r_pdt_political01'],
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_respawn01',		 	'r_pdt_respawn01'],
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_social01',			'r_pdt_social01'],
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_store01',				'r_pdt_store01'],
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_zHall01',				'r_pdt_zHall01'],
#['barkley2_mastermap02', 'undersewers/YsKolob/map_pdt_ZRoom01',				'r_pdt_zRoom01'],	
]
